import styles from "./page.module.css";
import backgroundImage from "../app/Images/01.jpg";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body bgColor="ff8247" className={styles.body}> 
        
        {children}</body>
    </html>
  )
}
